### ISSUE TITLE
Windows DLL Export

### ISSUE THREAD

**Issue by xtagon** [juan-cardelino/stasm#2]
Hi, thanks for making these CMake scripts. I am able to build a static library for Windows using your scripts, but I need a DLL. Version 3 of Stasm comes with a precompiled DLL, but version 4 doesn't.

What would it take to get a proper DLL exported for Windows? The README mentions it would "require some #defines". I realize you made these scripts as a volunteer effort and are probably busy, but can you give me a push in the right direction?

I have already tried modifying the generated Visual Studio project to produce a DLL instead of a static library, but I get a bunch of linker errors (all "unresolve symbols" seemingly for OpenCV):

```
Error   368 error LNK2001: unresolved external symbol "class cv::_OutputArray const & __cdecl cv::noArray(void)" (?noArray@cv@@YAABV_OutputArray@1@XZ)
```

Again, it builds fine if the target is a static .lib. Thanks in advance for your help!

**Comment by juan-cardelino** [comment]
Dear,
        xtagon. I'm pretty sure I've built dinamic libraries, not static ones. Do you have opencv built dynamic also? Because if you have only the static opencv that could explain the problem. Let me check it again and let you know.
Regarding the comment, I've found that the #defines are not required, it just works as it is.
Thanks for reporting this.

**Comment by xtagon** [comment]
Hi Juan,

Thanks for the reply. I'm building OpenCV as a dynamic library. It generates .DLLs for OpenCV in the `bin/Release` directory.

**Comment by juan-cardelino** [comment]
Dear xtagon,
            I will be testing this soon, and post somethign here. Let me know if you had any advances on this.
Regards,
             Juan

**Comment by xtagon** [comment]
Hi Juan,

My coworker figured out how to build the .DLL (I don't think he used the CMake scripts) and we've been using that successfully, so I haven't needed to revisit this. Thanks anyway for your help.

**Comment by juan-cardelino** [comment]
Ok. Glad to know it worked.
Regards.
